name: PuppeteerCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:bionic

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - name: install required packages
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0 libegl1 libgles2 libevent-2.1-6 libnotify4 libxslt1.1
      #     sudo apt-get install xvfb
      - name: npm install and test
        run: |
          npm install
          npm run test:ci
        env:
          CI: true
